# These are supported funding model platforms

github: # [dmitry-pavlov]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: dmitry_pavlov
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: dmitry-pavlov
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: https://paypal.me/dmitrycodingmachine
